spring.application.name=StudentManagementSystem
spring.datasource.url = jdbc:postgresql://localhost:5432/StudentManagementSystem
spring.datasource.username = postgres
spring.datasource.password = Pratibha@1

# hibernate is db inedependent so need to define PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# auto cretae table
spring.jpa.hibernate.ddl-auto = update